name: csocks build
on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build (with ${{ matrix.cc }})
        run: |
          CC=${{ matrix.cc }} make all

      - name: Run usage
        run: |
          ./csocks -h
